name: bsd_media
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & icons
  salomon_bottom_bar: ^3.3.2
  cupertino_icons: ^1.0.8
  line_icons: ^2.0.3
  line_awesome_flutter: ^3.0.1

  # intl url_launch
  intl: ^0.18.0
  url_launcher: ^6.1.7

  # Media
  video_player: ^2.5.0

  # Camera & file IO
  camera: ^0.11.1
  path_provider: ^2.0.14
  path: ^1.8.3

  googleapis: ^13.1.0
  google_sign_in: ^5.0.0

  # HTTP & JSON
  http: ^1.4.0

  # Firebase core
  firebase_core: ^3.14.0

  # Firebase Authentication
  firebase_auth: ^5.6.0

  # Cloud Firestore
  cloud_firestore: ^5.6.9

  #select file
  file_picker: ^10.2.0

  # Firebase Storage (for photos, QRIS, etc.)
  firebase_storage: ^12.4.7

  firebase_storage_web: ^3.10.14


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo-bsd-media.png
    - assets/vids/
    - assets/img/
