name: bsd_media
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & icons
  salomon_bottom_bar: ^3.3.2
  cupertino_icons: ^1.0.8
  line_icons: ^2.0.3
  line_awesome_flutter: ^3.0.1

  intl: ^0.20.2
  url_launcher: ^6.1.7
  cached_network_image: ^3.3.1
  image_picker: ^1.1.0
  video_player: ^2.5.0
  dio: ^5.1.2

  permission_handler: ^12.0.1
  camera: ^0.11.1
  path_provider: ^2.0.14

  path: ^1.8.3
  googleapis: ^13.1.0
  google_sign_in: ^7.1.0
  http: ^0.13.6

  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  file_picker: ^10.2.0
  firebase_storage: any

  firebase_storage_web: ^3.10.14
  cloud_functions: any

  flutter_downloader: ^1.11.6

  #donlot
  # gallery_saver: ^2.3.2
  # image_gallery_saver: ^2.0.3
  # image_downloader: ^0.31.0

  # flutter_prevent_screenshot: ^0.0.1+12

  firebase_app_check: any
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# This section is now correctly aligned at the root level
flutter:
  uses-material-design: true
  assets:
    - assets/logo-bsd-media.png
    - assets/vids/
    - assets/img/

  # Uncomment jika perlu menambah font LineAwesome manual
  # fonts:
  #   - family: LineAwesome
  #     fonts:
  #       - asset: assets/fonts/LineAwesome.ttf
